### ISSUE TITLE
problem in latest agile dotnet

### ISSUE THREAD

**Issue by developerss** [ribthegreat99OrN0P/Agile.NET-Deobfuscator-MOVED#10]
can decrypt delegate https://drive.google.com/file/d/1tWh_JElu5XI2LWRpmcES8DWJNqXSZ7p9/view?usp=sharing
see

**Comment by Maverick1983** [comment]
Sorry, I don't understand what you doing. Can you explain better?

**Comment by ribthegreat99OrN0P** [comment]
If you have a issue with latest agile, it will be all fixed soon havent been on GH in a while.

**Comment by developerss** [comment]
ok
