### ISSUE TITLE
"Feature Request" agile V.6.6 compatible

### ISSUE THREAD

**Issue by panzerknacker20111** [ribthegreat99OrN0P/Agile.NET-Deobfuscator-MOVED#11]
Hello,

today, I looked into the Source-Code to make the whole thing v6.6 compatible.

So first I looked, how the types 2XY= and 3XY= looked like in the 6.4 version. 

After that, I looked after the same code pattern in new dll files. 

So this is what I found so far:

Original 2XY= and 3XY=

```
`using System;

namespace l3U=
{
	// Token: 0x02000016 RID: 22
	public class 2XY= : 0XY=
	{
		// Token: 0x06000070 RID: 112 RVA: 0x000074F0 File Offset: 0x000056F0
		public 2XY=(Array target, uint objId)
		{
			this.23Y= = target;
			this.2nY= = (int)objId;
		}

		// Token: 0x06000071 RID: 113 RVA: 0x00007508 File Offset: 0x00005708
		public t3Y= 3HY=()
		{
			object value = this.23Y=.GetValue(this.2nY=);
			bool flag = value is t3Y=;
			t3Y= result;
			if (flag)
			{
				result = (t3Y=)value;
			}
			else
			{
				result = new t3Y=(value);
			}
			return result;
		}

		// Token: 0x06000072 RID: 114 RVA: 0x00007548 File Offset: 0x00005748
		public void 3XY=(t3Y= 3nY=)
		{
			Type elementType = this.23Y=.GetType().GetElementType();
			object value = (elementType == typeof(t3Y=)) ? 3nY= : 3nY=.vHY=();
			R3c=.X3c=(ref value, elementType);
			this.23Y=.SetValue(value, this.2nY=);
		}

		// Token: 0x04000051 RID: 81
		private int 2nY=;

		// Token: 0x04000052 RID: 82
		private Array 23Y=;
	}
}`
```

And this is what I think the same but from v.6.6 dll file:

```
`using System;

namespace nnU=
{
	// Token: 0x0200001D RID: 29
	public class aHc= : Pnc=
	{
		// Token: 0x060000BC RID: 188 RVA: 0x00002380 File Offset: 0x00000580
		public aHc=(Array target, uint objId)
		{
			this.anc= = target;
			this.aXc= = (int)objId;
		}

		// Token: 0x060000BD RID: 189 RVA: 0x00009B44 File Offset: 0x00007D44
		public Z3Y= a3c=()
		{
			object value = this.anc=.GetValue(this.aXc=);
			bool flag = value is Z3Y=;
			Z3Y= result;
			if (flag)
			{
				result = (Z3Y=)value;
			}
			else
			{
				result = new Z3Y=(value);
			}
			return result;
		}

		// Token: 0x060000BE RID: 190 RVA: 0x00009B84 File Offset: 0x00007D84
		public void bHc=(Z3Y= bXc=)
		{
			Type elementType = this.anc=.GetType().GetElementType();
			object value = (elementType == typeof(Z3Y=)) ? bXc= : bXc=.bHY=();
			13U=.73U=(ref value, elementType);
			this.anc=.SetValue(value, this.aXc=);
		}

		// Token: 0x04000073 RID: 115
		private int aXc=;

		// Token: 0x04000074 RID: 116
		private Array anc=;
	}
}`
```

So I changed 2XY= and 3XY= to aHc= and bHc=

But after compiling I still get "initialize field not found for string decryption" but why?

Any Ideas?

_Originally posted by @panzerknacker20111 in https://github.com/ribthegreat99OrN0P/Agile.NET-Deobfuscator/issues/8#issuecomment-913237351_

**Comment by code4bin** [comment]
Check what's the agile class name in your obfuscated exe and change it in source code of this solution for correct one in "Protection/StringDecryptionModule.cs" section (default is "<AgileDotNetRT>" - but agile v6.6 gives different class names in obfuscated exe (for example "<IKVM.OpenJDK.Reference>"). 

After that, the initialize field will be found and you'll see a lot of deobfuscated code (without correct method names).

In agile v6.6 method names are crypted by "dau" method in obfuscated exe - but I'm still working on this and implement it to this solution.

**Comment by digitalmedia34** [comment]
@code4bin can you provide more details. I played around with the code like you mentioned however, in my case is a bool instead of a byte[] so I am pretty sure I am doing something wrong.

**Comment by panzerknacker20111** [comment]
Thanks for your Answer, @code4bin 

But I already got that :) Interesting part -> in my example file it is actually <IKVM.OpenJDK.Reference>
And what I wrote above was just something I noticed by scrolling the source. It looks like the Values 2XY and 3XY which you are using in your version, has changed. Because I found the examt same code structure under the new values above.

Dont know if that is something "fix" in Version 6.6. or if its changing in every file.

In General it looks like Exe and Dll file has to "work together". I think thats maybe why I cant get any Strings decoded. (trying .dll)
If I try .exe it does find some strings to decrypt.

To get the .dll you just need to start the .exe and dump it with megadumper or something similar. In the Dumps folder you will find the AgileRuntime.dll (if it is not runnable, try "startsuspend" where you can set ms values an it will suspend the .exe process, which gives you any time you want to play with the procss)

@digitalmedia34 
He means the <AgileDotNetRT> part of any Agile .exe or .dll 
In Version 6.6. it could be anything. Like the mentioned "IKVM....."

![image](https://user-images.githubusercontent.com/53277885/136110519-271f9bf8-0d34-4d1e-9291-3d6cbbe3dcc9.png)

So inside the sourcecode of this deobfuscator you have to change <AgileDotNetRT> to your value.
You can easy find it with software like DNSPY or Dotnetreflector

**Comment by code4bin** [comment]
@panzerknacker20111 

After dump the file (megadumper or else as you mentioned) you need to proceed with jitdumper to get the hidden methods in the file (for example use the "ManagedJiterFr4.exe" app with your exe and make jit dump - remember to run the "ManagedJiterFr4.exe" in "NetBox40New.exe" app). 
There's a more jit app's that could fix hidden methods by Agile:
- ManagedJiterFr4
- SendToJitAndSaveFr4
- Simple_MSIL_Decryptor (need to be placed in the same folder where your obfuscated exe is)

After this, Agile.NET-Deobfuscator will find the decryption strings well and will deobfuscate ~90% of the file.

**Comment by code4bin** [comment]
@ @panzerknacker20111 
you can send me your file then I could check it and make few tricks on it. 
In my case the file was obfuscated by Themida 3.0.8.0 + Agile 6.6, so most probably I made wrong dump from Themida (exe didn't want to start but it's able to jit dump) and that's why I can't fully deobfuscate it from Agile.

**Comment by ribthegreat99OrN0P** [comment]
I will update this to work for latest agile soon.
