### ISSUE TITLE
Initialize field not found for string decryption

### ISSUE THREAD

**Issue by pequemec** [ribthegreat99OrN0P/Agile.NET-Deobfuscator-MOVED#8]
When loading a .dll library, “Initialize field not found for string decryption" appears. Several of the methods remain obfuscated. What solution is possible?

![Sample](https://user-images.githubusercontent.com/77752368/105379013-b1f63e00-5c0c-11eb-960f-1b6e197bec06.png)

**Comment by digitalmedia34** [comment]
It seems you are trying version 6.6 which doesnt work

**Comment by ribthegreat99OrN0P** [comment]
Hello, can you please provide the file

**Comment by pequemec** [comment]
[Sample.zip](https://github.com/ribthegreat99OrN0P/Agile.NET-Deobfuscator/files/5863014/Sample.zip)

**Comment by pequemec** [comment]
Hi,

As a newbie in reversing .NET packers i have a lot of troubles with Agile.
I never come with unpacking it without errors or crushes. I have tried
JitDumper4 with NetBox, also ManagedJiterFr4 and de4dot mod and all without
success. I would like to learn how to deobfuscate the file attached.

Thanks in advance.

**Comment by pequemec** [comment]
Sorry, I don't know how to send private.
Thanks in advance.

**Comment by komdil** [comment]
Is there any progess?

**Comment by towserchen** [comment]
Is there any progess?

**Comment by digitalmedia34** [comment]
Sample provided is corrupted or it has been modified.

**Comment by M1suzu** [comment]
@ribthegreat99OrN0P 
Hello, does this tool work against version 6.6? 
And can it deal with the VM of 6.6?

**Comment by Maverick1983** [comment]
No. Not working

Il Mer 21 Lug 2021, 01:24 Zhang ***@***.***> ha scritto:

**Comment by pequemec** [comment]
> Sample provided is corrupted or it has been modified.

Sample file is ok, any progess?

**Comment by panzerknacker20111** [comment]
Hello,

today, I looked into the Source-Code to make the whole thing v6.6 compatible.

So first I looked, how the types 2XY= and 3XY= looked like in the 6.4 version. 

After that, I looked after the same code pattern in new dll files. 

So this is what I found so far:

Original 2XY= and 3XY=

`using System;

namespace l3U=
{
	// Token: 0x02000016 RID: 22
	public class 2XY= : 0XY=
	{
		// Token: 0x06000070 RID: 112 RVA: 0x000074F0 File Offset: 0x000056F0
		public 2XY=(Array target, uint objId)
		{
			this.23Y= = target;
			this.2nY= = (int)objId;
		}

		// Token: 0x06000071 RID: 113 RVA: 0x00007508 File Offset: 0x00005708
		public t3Y= 3HY=()
		{
			object value = this.23Y=.GetValue(this.2nY=);
			bool flag = value is t3Y=;
			t3Y= result;
			if (flag)
			{
				result = (t3Y=)value;
			}
			else
			{
				result = new t3Y=(value);
			}
			return result;
		}

		// Token: 0x06000072 RID: 114 RVA: 0x00007548 File Offset: 0x00005748
		public void 3XY=(t3Y= 3nY=)
		{
			Type elementType = this.23Y=.GetType().GetElementType();
			object value = (elementType == typeof(t3Y=)) ? 3nY= : 3nY=.vHY=();
			R3c=.X3c=(ref value, elementType);
			this.23Y=.SetValue(value, this.2nY=);
		}

		// Token: 0x04000051 RID: 81
		private int 2nY=;

		// Token: 0x04000052 RID: 82
		private Array 23Y=;
	}
}`

And this is what I think the same but from v.6.6 dll file:

`using System;

namespace nnU=
{
	// Token: 0x0200001D RID: 29
	public class aHc= : Pnc=
	{
		// Token: 0x060000BC RID: 188 RVA: 0x00002380 File Offset: 0x00000580
		public aHc=(Array target, uint objId)
		{
			this.anc= = target;
			this.aXc= = (int)objId;
		}

		// Token: 0x060000BD RID: 189 RVA: 0x00009B44 File Offset: 0x00007D44
		public Z3Y= a3c=()
		{
			object value = this.anc=.GetValue(this.aXc=);
			bool flag = value is Z3Y=;
			Z3Y= result;
			if (flag)
			{
				result = (Z3Y=)value;
			}
			else
			{
				result = new Z3Y=(value);
			}
			return result;
		}

		// Token: 0x060000BE RID: 190 RVA: 0x00009B84 File Offset: 0x00007D84
		public void bHc=(Z3Y= bXc=)
		{
			Type elementType = this.anc=.GetType().GetElementType();
			object value = (elementType == typeof(Z3Y=)) ? bXc= : bXc=.bHY=();
			13U=.73U=(ref value, elementType);
			this.anc=.SetValue(value, this.aXc=);
		}

		// Token: 0x04000073 RID: 115
		private int aXc=;

		// Token: 0x04000074 RID: 116
		private Array anc=;
	}
}`

So I changed 2XY= and 3XY= to aHc= and bHc=

But after compiling I still get "initialize field not found for string decryption" but why?

Any Ideas?

**Comment by komdil** [comment]
https://drive.google.com/file/d/10J1J61HmzvmBxEpdrCbkQVU4cLBvgUj4/view?usp=sharing 

This file can be helpful for solving this issue

**Comment by ribthegreat99OrN0P** [comment]
will look into it soon sorry for long wait.

**Comment by Manggohype** [comment]
> When loading a .dll library, “Initialize field not found for string decryption" appears. Several of the methods remain obfuscated. What solution is possible?
> 
> ![Sample](https://user-images.githubusercontent.com/77752368/105379013-b1f63e00-5c0c-11eb-960f-1b6e197bec06.png)

Hello sir can i get your pre compiled version the latest is not working
